
#MINIXCAT3_DEFINES = -DCPU_LE 

#MINIXCAT3_CFLAGS=-c -Wall $(MINIXCAT3_DEFINES)

#LDFLAGS=

MINIXCAT3_SOURCES_DIR = $(MINIXCAT3_DRIVER_COMMON_DIR)/miniXcat3/src/init
MINIXCAT3_HEADER_DIR = $(MINIXCAT3_SOURCES_DIR)

MINIXCAT3_SOURCES = $(MINIXCAT3_SOURCES_DIR)/driver_pci.c \
  $(MINIXCAT3_SOURCES_DIR)/init_xc3.c

MINIXCAT3_OBJECTS=$(MINIXCAT3_SOURCES:.c=.o)

#EXECUTABLE=miniXcat3

#all: $(MINIXCAT3_SOURCES) $(EXECUTABLE)

#$(EXECUTABLE): $(OBJECTS) 
#	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

#.c.o:
#	$(CC) $(CFLAGS) $< -o $@

