#!/bin/sh
. /lib/functions.sh
. /lib/wifi/qcawifi.sh
. /lib/debug/dbg
DEV_NUM=2

wifi_firm_info(){
	local mac=""
	local cfgMac=""
	local change_flag=""
	local wps_pin=""
	local ssid=""
	for i in $(seq $DEV_NUM); do
		if [ -z "$(config_get ath$(($i-1)) wps_pin)" ]; then
			if [ -z "$wps_pin" ]; then
				wps_pin="$(getfirm PIN)"
			fi
			if [ "$(config_get ath$(($i-1)) device)" = "wifi$(($i-1))" ]; then
				uci set wireless.ath$(($i-1)).wps_pin=${wps_pin}
				uci set wireless.ath$(($i-1)).encryption="psk"
				uci set wireless.ath$(($i-1)).psk_key=${wps_pin}
				uci set wireless.ath$(($i-1)).wps_state=2
				change_flag="1"
			fi
			#default security of guest network is none.
			if [ "$(config_get ath$(($i-1))1 device)" = "wifi$(($i-1))" ]; then
				uci set wireless.ath$(($i-1))1.encryption="none"
				change_flag="1"
			fi
		fi
	done
	
	local idx=0
	cd /sys/class/net/
	[ -d wifi0 ] || load_qcawifi
	for dev in $(ls -d wifi* 2>$STDOUT); do
		case "$(cat ${dev}/hwcaps)" in
			*11bgn) mode_11=bgn;band="2g";;
			*11abgn) mode_11=bgn;band="2g";;
			*11an) mode_11=an_5;band="5g";;
			*11an/ac) mode_11=anac_5;band="5g";;
			*11abgn/ac) mode_11=anac_5;band="5g";;
		esac
		cfgMac="$(config_get wifi${idx} macaddr)"
		mac="$(getfirm MAC)"
		case $band in
			5g) mac=`mac_addr 2 $mac`;;
			*) ;;
		esac
		mac="$(echo $mac | tr 'a-f' 'A-F')"
		if [ -z "$cfgMac" ]; then
			uci set wireless.wifi${idx}.macaddr=$mac
			change_flag="1"
		elif [ "$mac" != "$cfgMac" ]; then
		uci set wireless.wifi${idx}.macaddr=$mac
			change_flag="1"
		else
			:
		fi
		if [ -z "$(config_get wifi${idx} band)" -o "$(config_get wifi${idx} band)" != ${band} ]; then
			uci set wireless.wifi${idx}.hwmode=${mode_11}
			uci set wireless.wifi${idx}.band=${band}
			change_flag="1"
			if [ -z "$ssid" ]; then
				ssid="$(getfirm SSID)"
			fi
			local suffix
			suffix=$(uci get wireless.wifi${idx}.macaddr|cut -d "-" -f 5,6 | sed 's/-//g'|tr 'a-f' 'A-F')

			[ "$band" = "5g" ] && suffix="${suffix}_${band//g/G}"
			
			if [ "$(config_get ath${idx} device)" = "wifi${idx}" ]; then
				uci set wireless.ath${idx}.ssid="${ssid}_${suffix}"
				#uci set wireless.ath${idx}.ssid="${ssid}_HOME_${band//g/G}"
			fi
			if [ "$(config_get ath${idx}1 device)" = "wifi${idx}" ]; then
				uci set wireless.ath${idx}1.ssid="${ssid}_Guest_${suffix}"
				#uci set wireless.ath${idx}1.ssid="${ssid}_GUEST_${band//g/G}"
			fi
		fi
		idx=$(($idx+1))
	done
	if [ -z "$(config_get wps model_name)" ]; then
		local model="$(getfirm MODEL)"
		uci set wireless.wps.model_name="${model}"
		change_flag="1"
	fi
	if [ -z "$(config_get wps wps_manufacturer)" -o -z "$(config_get wps wps_manufacturer_url)" ]; then
		local firm="$(getfirm FIRM)"
		local website="$(getfirm WEBSITE)"
		uci set wireless.wps.wps_manufacturer=${firm}
		uci set wireless.wps.wps_manufacturer_url=${website}
		change_flag="1"
	fi
	if [ "$change_flag" = "1" ]; then
	wifi_commit
	fi
}

config_load wireless
wifi_firm_info
