/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ubuntu 4.4.0-142-generic #168~14.04.1-Ubuntu SMP Sat Jan 19 11:28:33 UTC 2019 i686 athlon i686 GNU/Linux"
#define BUILD_ENV_DATE "Thu Dec  9 06:37:46 PST 2021"
#define BUILD_ENV_SRCDIR "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/target-mips_r2_uClibc-0.9.33.2/samba-3.6.5/source3"
#define BUILD_ENV_BUILDDIR "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/target-mips_r2_uClibc-0.9.33.2/samba-3.6.5/source3"
#define BUILD_ENV_USER "ubuntu"
#define BUILD_ENV_HOST "ubuntu"
#define BUILD_ENV_COMPILER "mips-openwrt-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
