#############################################################
#
# sdk 
#
#############################################################
SDK_VERSION = 1.0
SDK_SITE = $(TOPDIR)/tplink/sdk/sdk_dummy
SDK_SITE_METHOD = local
SDK_AUTORECONF = YES
SDK_INSTALL_STAGING = NO
SDK_INSTALL_TARGET =  YES

ifeq ($(BR2_TPLINK_CHIP_PLATFORM_DEF), "-D_CHIP_VENDOR_MARVELL_AC5")
SDK_TARGET_DIR = $(call qstrip,$(BR2_TPLINK_SDK_DIR))cpss
else 
SDK_TARGET_DIR = $(call qstrip,$(BR2_TPLINK_SDK_DIR))
endif

SDK_PROJECT_NAME = $(call qstrip,$(BR2_TPLINK_PROJECT_NAME))
SDK_DEBUG_FLAG = $(call qstrip,$(BR2_TPLINK_SDK_DBG))
#PP_TYPE DX_ALL PX_ALL DX/PX
SDK_SH_BUILD_PARAM += DX_ALL
#CPU & CHIPSET

ARM_CORE=ARMv7

ifeq ($(BR2_TPLINK_PROJECT_NAME), "TL_SX3008")
SDK_SH_BUILD_PARAM += ARMv7_LK_3_10
else ifeq ($(BR2_TPLINK_CHIP_PLATFORM_DEF), "-D_CHIP_VENDOR_MARVELL_AC5")
SDK_SH_BUILD_PARAM += AARCH64v8
ARM_CORE=""
else
SDK_SH_BUILD_PARAM += ARMv7_LK_4_4
endif
#OPTIONAL PARAMETERS

ifeq ($(BR2_TPLINK_CHIP_PLATFORM_DEF), "-D_CHIP_VENDOR_MARVELL_AC5")
SDK_SH_BUILD_PARAM += NOKERNEL CPSS_ENABLER_NOKM NOLUA NOGALTIS UTF_NO TM_NO NOLINK
else
SDK_SH_BUILD_PARAM +=  CUST NOKERNEL CPSS_ENABLER_NOKM NOLUA NOGALTIS UTF_NO TM_NO NOLINK
endif

#TPLINK PARAMETERS
#SDK_SH_BUILD_PARAM += TPLINK_$(SDK_PROJECT_NAME)

ifneq ($(BR2_TPLINK_CHIP_PLATFORM_DEF), "-D_CHIP_VENDOR_MARVELL_AC5")
SDK_SH_BUILD_PARAM += TPLINK_CUSTOM TPLINK_$(SDK_PROJECT_NAME)
endif

SDK_BUILD_DIR = $(SDK_TARGET_DIR)/$(SDK_PROJECT_NAME)

$(eval $(tplink-autotools-package))
