#!/bin/sh

inc_mac(){
	echo $1 | awk 'BEGIN{FS="-";add=1}{for(i=6;i>0;i--){j="0x"$i;\
	if(i>3){if(j+add>255){j=j+add-256;add=1;}else{j=j+add;add=0;}}printf("%02x",j);printf "-"}}' \
	| awk 'BEGIN{FS="-"}{for(i=6;i>0;i--){printf $i;if(i>1){printf "-"}}}'
}

dec_mac(){
	echo $1 | awk 'BEGIN{FS="-";dec=1}{for(i=6;i>0;i--){j="0x"$i;\
	if(i>3){if(j-dec<0){j=j-dec+256;dec=1;}else{j=j-dec;dec=0;}}printf("%02x",j);printf "-"}}' \
	| awk 'BEGIN{FS="-"}{for(i=6;i>0;i--){printf $i;if(i>1){printf "-"}}}'
}

local mac=$(getfirm MAC)

if [ "$1" == "lan" ]; then
    echo -n $mac
elif [ "$1" == "wan" ]; then
    mac=$(inc_mac $mac)
    echo -n $mac
elif [ "$1" == "lan_inc2" ]; then
	mac=$(inc_mac $mac)
	mac=$(inc_mac $mac)
	echo -n $mac
elif [ "$1" == "wireless_2.4" ]; then
    mac=$(dec_mac $mac)
    echo -n $mac
elif [ "$1" == "wireless_5" ]; then
    mac=$(dec_mac $mac)
    mac=$(dec_mac $mac)
    echo -n $mac
elif [ "$1" == "lan_dec1" ]; then
    mac=$(dec_mac $mac)
    echo -n $mac
elif [ "$1" == "lan_dec2" ]; then
    mac=$(dec_mac $mac)
    mac=$(dec_mac $mac)
    echo -n $mac
elif [ "$1" == "lan_dec3" ]; then
	mac=$(dec_mac $mac)
	mac=$(dec_mac $mac)
	mac=$(dec_mac $mac)
	echo -n $mac
fi
