# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /home/ubuntu/Archer_C7_V5/openwrt/build_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/gcc-linaro-4.6-2012.02/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
