/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("ieee802dot11")) shutdown_ieee802dot11();
  if (should_init("ifXTable")) shutdown_ifXTable();
  if (should_init("cpu")) shutdown_cpu();
  if (should_init("ifTable")) shutdown_ifTable();
