#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

alias l='ls -l'
alias ll='ls -la'
[ ! -f /lib/modules/`uname -r`/modules.dep ] && depmod -a

####### tftp shortcut
local tftp_ser="192.168.1.100"
down()
{
	local list="$1"
	for ff in $list; do
		tftp -gr $ff $tftp_ser
	done
}
up()
{
	local list="$1"
	for ff in $list; do
		tftp -pr $ff $tftp_ser
	done
}

####### linux app coredump generate
#ulimit -c unlimited
#echo /tmp/coredump_%e_%t_%p > /proc/sys/kernel/core_pattern
ulimit -c 20000
echo /tmp/coredump_%e_%p > /proc/sys/kernel/core_pattern

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
