
all:logApi logServer demo tools shellApi
	make -C logApi
	make -C logServer
	make -C demo
	make -C tools
	make -C shellApi
	
clean:
	make clean -C logApi
	make clean -C logServer
	make clean -C demo
	make clean -C tools
	make clean -C shellApi
