#!/bin/sh
. /lib/functions.sh
. /lib/netifd/netifd-proto.sh

PPP_IPPARAM="$6"

dhcp6cdir="/tmp/dhcp6c"
conffile="$dhcp6cdir/dhcp6c.conf"
dhcp6cpid="$dhcp6cdir/dhcp6c.pid"
dhcp6cscript="/lib/netifd/pppshare-dhcp6c.script"
proto_dhcp6c_create_conffile(){
	local ip_mode="$1"
	local dns_mode="$2"
	local ifname="$3"
	local lanif="$4"
	local ip_config="$5"
	#local id=`date +%s`

	#id=`expr $id % 1000000`

	#local id2=`expr $id + 1`
	local id=1
	local id2=$id

	rm -rf ${dhcp6cdir}
	mkdir -p ${dhcp6cdir}
	#echo create conffile : $ip_config:$ip_mode:$ifname > /dev/console
	if [ "$ip_config" == "specified" ]; then
		echo "interface $ifname {" > "${conffile}"

		[ "$dns_mode" == "dynamic" ] && echo -e "\trequest domain-name-servers;" >> "${conffile}"
		echo -e "\tscript \"$dhcp6cscript\";" >> "${conffile}"

		echo "};" >>  "${conffile}"

	else
		[ "$ip_mode" == "prefix" ] && {

			echo "interface $ifname {" > "${conffile}"
			[ "$ip_config" == "dhcpv6" ] && echo -e "\tsend ia-na $id;" >> "${conffile}"
			echo -e "\tsend ia-pd $id2;" >> "${conffile}"

			[ "$dns_mode" == "dynamic" ] && echo -e "\trequest domain-name-servers;" >> "${conffile}"
			echo -e "\tscript \"$dhcp6cscript\";" >> "${conffile}"

			echo -e "};\n" >>  "${conffile}"

			echo -e "id-assoc na $id {};\n" >> "${conffile}"

			echo "id-assoc pd $id2 {" >> "${conffile}"
			echo -e "\tprefix-interface $lanif {" >> "${conffile}"
			echo -e "\t\tsla-id 1;" >> "${conffile}"
			echo -e "\t};" >>  "${conffile}"
			echo "};" >>  "${conffile}"
		}
		[ "$ip_mode" == "non_temp" ] && {
			echo "interface $ifname {" > "${conffile}"
			[ "$ip_config" == "dhcpv6" ] && echo -e "\tsend ia-na $id;" >> "${conffile}"
			[ "$ip_config" == "slaac" ] && echo -e "\tinformation-only;" >> "${conffile}"
			[ "$dns_mode" == "dynamic" ] && echo -e "\trequest domain-name-servers;" >> "${conffile}"
			echo -e "\tscript \"$dhcp6cscript\";" >> "${conffile}"

			echo "};" >>  "${conffile}"

			echo "id-assoc na $id {};" >> "${conffile}"
		}
	fi
}
dhcp6c_write_duid() {
	local client_device="$2"
	local mac="${1:-$(ifconfig "$client_device" | sed -ne 's/[[:space:]]*$//; s/.*HWaddr //p')}"
	local pat="[0-9A-F][0-9A-F]"
	case "$mac" in
		# exactly 6 octets -> assume type 3 (DUID-LL - RFC3315, 9.4)
		$pat:$pat:$pat:$pat:$pat:$pat)
			local oIFS="$IFS"; IFS=":"; set -- $mac; IFS="$oIFS"

			# low endian
			if [ "$(printf \\1 | hexdump -n1 -ve '8/2 "" "%04x" ""')" = "0001" ]; then
				printf \\x0a\\x00

			# big endian
			else
				printf \\x00\\x0a
			fi

			printf \\x00\\x03\\x00\\x06\\x$1\\x$2\\x$3\\x$4\\x$5\\x$6
			logger -t dhcp6c "Using MAC address DUID 00:03:00:06:$1:$2:$3:$4:$5:$6"
		;;
		# at least 7 octets -> could be type 1 or type 2
		$pat:$pat:$pat:$pat:$pat:$pat:*)
			local len_id=":$(echo "$mac" | sed -e 's/[^:]//g')"
			local len_hi=$(printf "%02x" $((${#len_id} / 0xFF)) )
			local len_lo=$(printf "%02x" $((${#len_id} % 0xFF)) )

			# low endian
			if [ "$(printf \\1 | hexdump -n1 -ve '8/2 "" "%04x" ""')" = "0001" ]; then
				printf \\x$len_lo\\x$len_hi

			# big endian
			else
				printf \\x$len_hi\\x$len_lo
			fi

			printf $(echo "$mac" | sed -e 's/^/\\x/; s/:/\\x/g')
			logger -t dhcp6c "Using user provided DUID $mac"
		;;
		*)
			logger -t dhcp6c "Unable to derive DUID from interface '$client_device' and no valid user DUID given"
		;;
	esac
}

config_load /etc/config/network
config_get ip_config wan ip_config
config_get ipv6_mode internet ipv6_mode
config_get dnsv6_mode internet dnsv6_mode
config_get ip6addr wan ip6addr
config_get lanif wan lanif
config_get ipv4 wan ipv4
config_get dhcp_ifname wan ifname
config_get user_duid basic duid

ppp_up="/tmp/pppv6/ppp_up"
#rm -rf /tmp/pppv6

#echo ppp share up: $IPREMOTE : $LLREMOTE  > /dev/console

[ -n "$LLREMOTE" ] || exit 1

#echo ip_config: $ip_config > /dev/console
network_echo $LOG_PRI_NOTICE "pppshare" "$IFNAME link up"
if [ "$ip_config" == "specified" ]; then

	[ -n "$LLREMOTE" ] && {
		proto_init_update "$IFNAME" 1 1
		proto_set_keep 1

		[ -n "$PPP_IPPARAM" ] && {
			[ -n "$LLLOCAL" ] && proto_add_ipv6_address "$LLLOCAL" 64
			[ -n "$ip6addr" ] && {
				ip -6 addr add "$ip6addr/64" dev "$IFNAME"
				proto_add_ipv6_address "$ip6addr" 64
			}
			[ -n "$LLREMOTE" ] && proto_add_ipv6_route "::" 0 "$LLREMOTE"
			[ -n "$DNS1" ] && [ "$ipv4" == "1" ] && proto_add_dns_server "$DNS1"
			[ -n "$DNS2" ] && [ "$DNS1" != "$DNS2" ] && [ "$ipv4" == "1" ] && proto_add_dns_server "$DNS2"

			if [ -n "$ip6addr" ]; then
				local ndp_prefix=$(lua /lib/netifd/lanv6_genrate_ndp_prefix.lua $ip6addr)
				echo "$ndp_prefix" > /tmp/dhcp6c/ndp_prefix
			fi
		}
		proto_send_update "$PPP_IPPARAM"
	}

else
	[ -n "$PPP_IPPARAM" ] && [ -n "$LLREMOTE" ] && {
		mkdir -p /tmp/pppv6
		[ -n "$LLLOCAL" ] && echo "$LLLOCAL" >> "$ppp_up" || echo "none" >> "$ppp_up"
		[ -n "$LLREMOTE" ] && echo "$LLREMOTE" >> "$ppp_up" || echo "none" >> "$ppp_up"
		[ -n "$DNS1" ] && [ "$ipv4" == "1" ] && echo "$DNS1" >> "$ppp_up" || echo "none" >> "$ppp_up"
		[ -n "$DNS2" ] && [ "$DNS1" != "$DNS2" ] && [ "$ipv4" == "1" ] && echo "$DNS2" >> "$ppp_up" ||  echo "none" >> "$ppp_up"
		local up_info=$(cat ${ppp_up})
		network_echo $LOG_PRI_DEBUG "pppshare" "ip info:$up_info"
	}
fi

[ -n "$LLREMOTE" ] && {

	local mbit=-1
	local count=15
	
	if [ $ip_config == "slaac" ] || [ $ip_config == "auto" ]; then
		echo "1"  > /proc/sys/net/ipv6/conf/$ifname/accept_ra_pinfo
	else
		echo "0"  > /proc/sys/net/ipv6/conf/$ifname/accept_ra_pinfo
	fi

	echo "-1" > /proc/sys/net/ipv6/conf/$IFNAME/ndisc_mbit #reset the mbit value to -1
	echo "2"  > /proc/sys/net/ipv6/conf/$IFNAME/accept_ra
	echo "1" > /proc/sys/net/ipv6/conf/$IFNAME/sendrs  #send RS for RA

	# [ "$ip_config" == "auto" ] && {
		# wait for RA
		echo mbit begin:$mbit > /dev/console
		mbit=$(cat /proc/sys/net/ipv6/conf/$IFNAME/ndisc_mbit)
		while [ $count -ne 0 ] && [ $mbit -eq -1 ]; do
			echo mbit:$mbit > /dev/console
			sleep 1
			mbit=$(cat /proc/sys/net/ipv6/conf/$IFNAME/ndisc_mbit)
			let "count=count - 1"
			echo mbit:$mbit > /dev/console
		done

		[ "$ip_config" == "auto" ] && {
			# if timeout or mbit != 0, restart
			if [ $mbit -eq 0 ]; then
				ip_config="slaac"
			elif [ $mbit -eq 1 ];then
				ip_config="dhcpv6"
			else
				#echo setup mbit:$mbit > /dev/console
				sleep 3
				proto_setup_failed "$PPP_IPPARAM"
				return
			fi
		}
	# }

	network_echo $LOG_PRI_DEBUG "pppshare" "create config, ipv6_mode=$ipv6_mode dnsv6_mode=$dnsv6_mode IFNAME=$IFNAME lanif=$lanif ip_config=$ip_config"
	proto_dhcp6c_create_conffile "$ipv6_mode" "$dnsv6_mode" "$IFNAME" "$lanif" "$ip_config"
	#local duid_file="/var/dhcp6c_duid"
	#dhcp6c_write_duid "$user_duid" "$dhcp_ifname" > $duid_file
	local dhcp_ifname_file="/tmp/pppv6_dhcp_ifname"
	echo $dhcp_ifname > $dhcp_ifname_file
	sleep 1
	#echo ppp:$PPP_IPPARAM $IFNAME > /dev/console
	network_echo $LOG_PRI_NOTICE "pppshare" "call dhcp6c to get ipv6 info"
	/usr/sbin/dhcp6c -f -p "$dhcp6cpid" -c "$conffile" -t "$PPP_IPPARAM" "$IFNAME" &
}

[ -d /etc/ppp/ip-up.d  -a -n "$LLREMOTE" ] && {
	for SCRIPT in /etc/ppp/ip-up.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}
