#
# Makefile for http stuff
#
ccflags-y += -fno-strict-aliasing
obj-y += uip.o
obj-y += uip_arch.o
obj-y += uip_arp.o
obj-y += httpd.o
obj-y += fs.o

#########################################################################

