/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef ITABLE_H
#define ITABLE_H

typedef enum {
#line 94 "./mips.igen"
  itable_RSVD_SPECIAL,
#line 507 "./mips.igen"
  itable_ADD_SPECIAL,
#line 535 "./mips.igen"
  itable_ADDI_NORMAL,
#line 572 "./mips.igen"
  itable_ADDIU_NORMAL,
#line 601 "./mips.igen"
  itable_ADDU_SPECIAL,
#line 628 "./mips.igen"
  itable_AND_SPECIAL,
#line 648 "./mips.igen"
  itable_ANDI_NORMAL,
#line 670 "./mips.igen"
  itable_BEQ_NORMAL,
#line 694 "./mips.igen"
  itable_BEQL_NORMAL,
#line 719 "./mips.igen"
  itable_BGEZ_REGIMM,
#line 743 "./mips.igen"
  itable_BGEZAL_REGIMM,
#line 770 "./mips.igen"
  itable_BGEZALL_REGIMM,
#line 800 "./mips.igen"
  itable_BGEZL_REGIMM,
#line 825 "./mips.igen"
  itable_BGTZ_NORMAL,
#line 849 "./mips.igen"
  itable_BGTZL_NORMAL,
#line 876 "./mips.igen"
  itable_BLEZ_NORMAL,
#line 902 "./mips.igen"
  itable_BLEZL_NORMAL,
#line 927 "./mips.igen"
  itable_BLTZ_REGIMM,
#line 951 "./mips.igen"
  itable_BLTZAL_REGIMM,
#line 980 "./mips.igen"
  itable_BLTZALL_REGIMM,
#line 1008 "./mips.igen"
  itable_BLTZL_REGIMM,
#line 1035 "./mips.igen"
  itable_BNE_NORMAL,
#line 1059 "./mips.igen"
  itable_BNEL_NORMAL,
#line 1084 "./mips.igen"
  itable_BREAK_SPECIAL,
#line 1432 "./mips.igen"
  itable_DIV_SPECIAL,
#line 1473 "./mips.igen"
  itable_DIVU_SPECIAL,
#line 1884 "./mips.igen"
  itable_J_NORMAL,
#line 1906 "./mips.igen"
  itable_JAL_NORMAL,
#line 1928 "./mips.igen"
  itable_JALR_SPECIAL,
#line 1960 "./mips.igen"
  itable_JR_SPECIAL,
#line 2096 "./mips.igen"
  itable_LB_NORMAL,
#line 2115 "./mips.igen"
  itable_LBU_NORMAL,
#line 2199 "./mips.igen"
  itable_LH_NORMAL,
#line 2218 "./mips.igen"
  itable_LHU_NORMAL,
#line 2237 "./mips.igen"
  itable_LL_NORMAL,
#line 2318 "./mips.igen"
  itable_LUI_NORMAL,
#line 2339 "./mips.igen"
  itable_LW_NORMAL,
#line 2358 "./mips.igen"
  itable_LWCz_NORMAL,
#line 2377 "./mips.igen"
  itable_LWL_NORMAL,
#line 2396 "./mips.igen"
  itable_LWR_NORMAL,
#line 2524 "./mips.igen"
  itable_MFHI_SPECIAL,
#line 2563 "./mips.igen"
  itable_MFLO_SPECIAL,
#line 2594 "./mips.igen"
  itable_MOVN_SPECIAL,
#line 2613 "./mips.igen"
  itable_MOVZ_SPECIAL,
#line 2714 "./mips.igen"
  itable_MTHI_SPECIAL,
#line 2745 "./mips.igen"
  itable_MTLO_SPECIAL,
#line 2813 "./mips.igen"
  itable_MULT_SPECIAL,
#line 2879 "./mips.igen"
  itable_MULTU_SPECIAL,
#line 2933 "./mips.igen"
  itable_NOR_SPECIAL,
#line 2959 "./mips.igen"
  itable_OR_SPECIAL,
#line 2986 "./mips.igen"
  itable_ORI_NORMAL,
#line 3005 "./mips.igen"
  itable_PREF_NORMAL,
#line 3153 "./mips.igen"
  itable_SB_NORMAL,
#line 3172 "./mips.igen"
  itable_SC_NORMAL,
#line 3322 "./mips.igen"
  itable_SH_NORMAL,
#line 3349 "./mips.igen"
  itable_SLLa_SPECIAL,
#line 3392 "./mips.igen"
  itable_SLLV_SPECIAL,
#line 3418 "./mips.igen"
  itable_SLT_SPECIAL,
#line 3444 "./mips.igen"
  itable_SLTI_NORMAL,
#line 3470 "./mips.igen"
  itable_SLTIU_NORMAL,
#line 3497 "./mips.igen"
  itable_SLTU_SPECIAL,
#line 3526 "./mips.igen"
  itable_SRA_SPECIAL,
#line 3557 "./mips.igen"
  itable_SRAV_SPECIAL,
#line 3587 "./mips.igen"
  itable_SRL_SPECIAL,
#line 3617 "./mips.igen"
  itable_SRLV_SPECIAL,
#line 3636 "./mips.igen"
  itable_SUB_SPECIAL,
#line 3672 "./mips.igen"
  itable_SUBU_SPECIAL,
#line 3691 "./mips.igen"
  itable_SW_NORMAL,
#line 3710 "./mips.igen"
  itable_SWCz_NORMAL,
#line 3729 "./mips.igen"
  itable_SWL_NORMAL,
#line 3748 "./mips.igen"
  itable_SWR_NORMAL,
#line 3767 "./mips.igen"
  itable_SYNC_SPECIAL,
#line 3786 "./mips.igen"
  itable_SYSCALL_SPECIAL,
#line 3805 "./mips.igen"
  itable_TEQ_SPECIAL,
#line 3823 "./mips.igen"
  itable_TEQI_REGIMM,
#line 3841 "./mips.igen"
  itable_TGE_SPECIAL,
#line 3859 "./mips.igen"
  itable_TGEI_REGIMM,
#line 3877 "./mips.igen"
  itable_TGEIU_REGIMM,
#line 3895 "./mips.igen"
  itable_TGEU_SPECIAL,
#line 3913 "./mips.igen"
  itable_TLT_SPECIAL,
#line 3931 "./mips.igen"
  itable_TLTI_REGIMM,
#line 3949 "./mips.igen"
  itable_TLTIU_REGIMM,
#line 3967 "./mips.igen"
  itable_TLTU_SPECIAL,
#line 3985 "./mips.igen"
  itable_TNE_SPECIAL,
#line 4003 "./mips.igen"
  itable_TNEI_REGIMM,
#line 4028 "./mips.igen"
  itable_XOR_SPECIAL,
#line 4054 "./mips.igen"
  itable_XORI_NORMAL,
#line 4273 "./mips.igen"
  itable_ABS_fmt_COP1,
#line 4296 "./mips.igen"
  itable_ADD_fmt_COP1,
#line 4377 "./mips.igen"
  itable_BC1b_COP1S,
#line 4415 "./mips.igen"
  itable_C_cond_fmtb_COP1,
#line 4436 "./mips.igen"
  itable_CEIL_L_fmt_COP1,
#line 4455 "./mips.igen"
  itable_CEIL_W_COP1,
#line 4490 "./mips.igen"
  itable_CFC1b_COP1,
#line 4539 "./mips.igen"
  itable_CTC1b_COP1,
#line 4572 "./mips.igen"
  itable_CVT_D_fmt_COP1,
#line 4596 "./mips.igen"
  itable_CVT_L_fmt_COP1,
#line 4634 "./mips.igen"
  itable_CVT_S_fmt_COP1,
#line 4684 "./mips.igen"
  itable_CVT_W_fmt_COP1,
#line 4708 "./mips.igen"
  itable_DIV_fmt_COP1,
#line 4808 "./mips.igen"
  itable_FLOOR_L_fmt_COP1,
#line 4827 "./mips.igen"
  itable_FLOOR_W_fmt_COP1,
#line 4859 "./mips.igen"
  itable_LDC1b_COP1,
#line 4935 "./mips.igen"
  itable_LWC1_COP1,
#line 4955 "./mips.igen"
  itable_LWXC1_COP1X,
#line 4971 "./mips.igen"
  itable_MADD_fmt_COP1X,
#line 5002 "./mips.igen"
  itable_MFC1b_COP1,
#line 5020 "./mips.igen"
  itable_MOV_fmt_COP1,
#line 5044 "./mips.igen"
  itable_MOVtf_SPECIAL,
#line 5062 "./mips.igen"
  itable_MOVtf_fmt_COP1,
#line 5093 "./mips.igen"
  itable_MOVN_fmt_COP1,
#line 5118 "./mips.igen"
  itable_MOVZ_fmt_COP1,
#line 5136 "./mips.igen"
  itable_MSUB_fmt_COP1X,
#line 5168 "./mips.igen"
  itable_MTC1b_COP1,
#line 5185 "./mips.igen"
  itable_MUL_fmt_COP1,
#line 5207 "./mips.igen"
  itable_NEG_fmt_COP1,
#line 5229 "./mips.igen"
  itable_NMADD_fmt_COP1X,
#line 5247 "./mips.igen"
  itable_NMSUB_fmt_COP1X,
#line 5293 "./mips.igen"
  itable_PREFX_COP1X,
#line 5342 "./mips.igen"
  itable_RECIP_fmt_COP1,
#line 5357 "./mips.igen"
  itable_ROUND_L_fmt_COP1,
#line 5376 "./mips.igen"
  itable_ROUND_W_fmt_COP1,
#line 5397 "./mips.igen"
  itable_RSQRT_fmt_COP1,
#line 5423 "./mips.igen"
  itable_SDC1b_COP1,
#line 5499 "./mips.igen"
  itable_SQRT_fmt_COP1,
#line 5519 "./mips.igen"
  itable_SUB_fmt_COP1,
#line 5542 "./mips.igen"
  itable_SWC1_COP1,
#line 5588 "./mips.igen"
  itable_SWXC1_COP1X,
#line 5632 "./mips.igen"
  itable_TRUNC_L_fmt_COP1,
#line 5651 "./mips.igen"
  itable_TRUNC_W_COP1,
#line 5679 "./mips.igen"
  itable_BC0F_COP0,
#line 5702 "./mips.igen"
  itable_BC0FL_COP0,
#line 5717 "./mips.igen"
  itable_BC0T_COP0,
#line 5731 "./mips.igen"
  itable_BC0TL_COP0,
#line 5746 "./mips.igen"
  itable_CACHE_NORMAL,
#line 5797 "./mips.igen"
  itable_ERET_COP0,
#line 5824 "./mips.igen"
  itable_MFC0_COP0,
#line 5844 "./mips.igen"
  itable_MTC0_COP0,
#line 5863 "./mips.igen"
  itable_RFE_COP0,
#line 5878 "./mips.igen"
  itable_COPz_NORMAL,
#line 5897 "./mips.igen"
  itable_TLBP_COP0,
#line 5912 "./mips.igen"
  itable_TLBR_COP0,
#line 5927 "./mips.igen"
  itable_TLBWI_COP0,
#line 5942 "./mips.igen"
  itable_TLBWR_COP0,
  nr_itable_entries,
} itable_index;

typedef enum {
  itable_flag_32,
  itable_flag_f,
  nr_itable_flags,
} itable_flags;
extern const char *itable_flag_names[];

typedef enum {
  nr_itable_options,
} itable_options;
extern const char *itable_option_names[];

typedef enum {
  itable_processor_dsp,
  itable_processor_dsp2,
  itable_processor_mdmx,
  itable_processor_mips16,
  itable_processor_mips16e,
  itable_processor_mips32,
  itable_processor_mips32r2,
  itable_processor_mips3d,
  itable_processor_mips64,
  itable_processor_mips64r2,
  itable_processor_mipsI,
  itable_processor_mipsII,
  itable_processor_mipsIII,
  itable_processor_mipsIV,
  itable_processor_mipsV,
  itable_processor_r3900,
  itable_processor_sb1,
  itable_processor_smartmips,
  itable_processor_vr4100,
  itable_processor_vr4120,
  itable_processor_vr5000,
  itable_processor_vr5400,
  itable_processor_vr5500,
  nr_itable_processors,
} itable_processors;
extern const char *itable_processor_names[];

typedef struct _itable_instruction_info {
  itable_index nr;
  char *format;
  char *form;
  char *flags;
  char flag[nr_itable_flags + 1];
  char *options;
  char option[nr_itable_options + 1];
  char *processors;
  char processor[nr_itable_processors + 1];
  char *name;
  char *file;
  int line_nr;
} itable_info;

extern itable_info itable[nr_itable_entries];

enum {
  sizeof_itable_form = 8,
  sizeof_itable_name = 12,
  sizeof_itable_file = 10,
};

#endif /* _ITABLE_H_*/
