# CMake generated Testfile for 
# Source directory: /home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests
# Build directory: /home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(CMake.List "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/ListTest.cmake")
ADD_TEST(CMake.VariableWatch "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/VariableWatchTest.cmake")
ADD_TEST(CMake.Include "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/IncludeTest.cmake")
ADD_TEST(CMake.FindBase "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/FindBaseTest.cmake")
ADD_TEST(CMake.Toolchain "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/ToolchainTest.cmake")
ADD_TEST(CMake.GetFilenameComponentRealpath "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
ADD_TEST(CMake.Version "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/VersionTest.cmake")
ADD_TEST(CMake.Message "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/MessageTest.cmake")
ADD_TEST(CMake.File "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/FileTest.cmake")
ADD_TEST(CMake.ConfigureFile "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/ConfigureFileTest.cmake")
ADD_TEST(CMake.SeparateArguments "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/SeparateArgumentsTest.cmake")
ADD_TEST(CMake.ImplicitLinkInfo "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
ADD_TEST(CMake.ModuleNotices "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/ModuleNoticesTest.cmake")
ADD_TEST(CMake.GetProperty "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/GetPropertyTest.cmake")
ADD_TEST(CMake.If "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/IfTest.cmake")
ADD_TEST(CMake.String "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/StringTest.cmake")
ADD_TEST(CMake.Math "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/MathTest.cmake")
ADD_TEST(CMake.CMakeMinimumRequired "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
ADD_TEST(CMake.CompilerIdVendor "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/CompilerIdVendorTest.cmake")
ADD_TEST(CMake.ProcessorCount "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/ProcessorCountTest.cmake")
ADD_TEST(CMake.PushCheckState "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/PushCheckStateTest.cmake")
ADD_TEST(CMake.While "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/WhileTest.cmake")
ADD_TEST(CMake.FileDownload "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/FileDownloadTest.cmake")
SET_TESTS_PROPERTIES(CMake.FileDownload PROPERTIES  PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum")
ADD_TEST(CMake.FileUpload "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/FileUploadTest.cmake")
ADD_TEST(CMake.ELF "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/ELFTest.cmake")
ADD_TEST(CMake.EndStuff "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-Ddir:STRING=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/EndStuffTest" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/EndStuffTest.cmake")
ADD_TEST(CMake.GetPrerequisites "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCTEST_CONFIGURATION_TYPE:STRING=${CTEST_CONFIGURATION_TYPE}" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/GetPrerequisitesTest.cmake")
ADD_TEST(CMake.CheckSourceTree "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCMake_BINARY_DIR:PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9" "-DCMake_SOURCE_DIR:PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-DHOME:STRING=/home/ubuntu" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/CMakeTests/CheckSourceTreeTest.cmake")
