#!/bin/sh
#
# Copyright (c) 2014 TP-LINK Technologies Co., Ltd.
#
# All Rights Reserved.
#

IFNAME=$1
CMD=$2

case "$CMD" in
	WPS-NEW-AP-SETTINGS)
		source /sbin/wifi wps $IFNAME config | (
			local ssid enc ver cipher key wps_state val
			while read l; do
				val="$(echo $l | cut  -f2- -d=)"
				case "$(echo $l | cut  -f1 -d=)" in
					ssid)ssid="$val";;
					passphrase)key="$val";;
					wps_state)wps_state="$val";;
					wpa_pairwise)
						case "$val" in
							CCMP|AES)cipher="aes";;
							TKIP)cipher="tkip";;
							*)cipher="auto";;
						esac
						;;
					wpa)
						case "$val" in
							1)enc="psk";ver="wpa";;
							2)enc="psk";ver="rsn";;
							3)enc="psk";ver="auto";;
							0)enc="none";;
						esac
						;;
				esac
			done
			[ -n "$enc" -a -n "$ssid" ] && {
				uci set wireless.${IFNAME}.wps_state="$wps_state"
				uci set wireless.${IFNAME}.ssid="$ssid"
				uci set wireless.${IFNAME}.encryption="$enc"
				[ "$enc" = "psk" ] && {
					uci set wireless.${IFNAME}.psk_version="$ver"
					uci set wireless.${IFNAME}.psk_cipher="$cipher"
					uci set wireless.${IFNAME}.psk_key="$key"
				}
				wifi_commit
			})
		#kill "$(cat "/var/run/hostapd-cli-$IFNAME.pid")"
		#post hotplug event to whom take care of
		#env -i ACTION="wps-configured" INTERFACE=$IFNAME /sbin/hotplug-call iface
		;;
	WPS-PBC-ACTIVE)
		#kill "$(cat "/var/run/hostapd-cli-$IFNAME.pid")"
		#env -i ACTION="wps-timeout" INTERFACE=$IFNAME /sbin/hotplug-call iface
		;;
	WPS-OVERLAP-DETECTED)
		#kill "$(cat "/var/run/hostapd-cli-$IFNAME.pid")"
		#env -i ACTION="wps-timeout" INTERFACE=$IFNAME /sbin/hotplug-call iface
		;;
	WPS-FAIL)
		#kill "$(cat "/var/run/hostapd-cli-$IFNAME.pid")"
		#env -i ACTION="wps-timeout" INTERFACE=$IFNAME /sbin/hotplug-call iface
		;;
	WPS-TIMEOUT)
		#kill "$(cat "/var/run/hostapd-cli-$IFNAME.pid")"
		#env -i ACTION="wps-timeout" INTERFACE=$IFNAME /sbin/hotplug-call iface
		;;
	WPS-SUCCESS)
		#kill "$(cat "/var/run/hostapd-cli-$IFNAME.pid")"
		#env -i ACTION="wps-timeout" INTERFACE=$IFNAME /sbin/hotplug-call iface
		;;
	DISCONNECTED)
		#kill "$(cat "/var/run/hostapd_cli-$IFNAME.pid")"
		;;
esac
