#!/bin/sh

clear_port_mirror()
{
	#the default_port can be any port 
	local default_port=0

	swconfig dev switch0 port $default_port set mirrors ""
}

# enable port mirror
# $1:mirror mode
# $2:mirror port id
# $3:mirrored port list
enable_port_mirror()
{
	local mode=$1
	local mirrorport=$2
	local mirroredPortlist=$3
	local mirrorCmd=""
	
	for i in $mirroredPortlist; do		
	    let i=i-1
		if [ $mode = "ingress" ]; then
			mirrorCmd="${mirrorCmd}"" ""${i}"
		elif [ $mode = "egress" ]; then
			mirrorCmd="${mirrorCmd}"" ""${i}""t"
		elif [ $mode = "both" ]; then
			mirrorCmd="${mirrorCmd}"" ""${i}"" ""${i}""t"
		fi
	done	

	let mirrorport=mirrorport-1
	swconfig dev switch0 port $mirrorport set mirrors "$mirrorCmd"
}

mirror_usage()
{
	echo ""
	echo "Usage: switch -t mirror -o <get|set> [-s state] [-m mode] [-P mirrorport] [-p mirroredports]"
	echo ""
	echo "Example:"
	echo "       switch -t mirror -o get"
	echo "       switch -t mirror -o set -s on -m ingress -P 3 -p \"1 2 4\" "
	echo ""
}

# check mode mirror port and mirrored portlist
# exit when arg is invalid
# $1: mode
# $2: mirror port
# $3: mirrored ports
mirror_arg_check()
{
	local mode=$1
	local portid=$2
	local ports=$3

    if [ "$mode" != "" ] && [ "$mode" != "ingress" ] && [ "$mode" != "egress" ] && [ "$mode" != "both" ]; then
    	echo "[mirror] mode is error. (ingress | egress | both)"
        mirror_usage
        exit 0 
    fi 

    # check input portid
	if [ -z $portid ] || [ `expr match $portid "[0-9]"` = 0 ] || [ $portid -lt 1 ] || [ $portid -gt 5 ];then
		echo "[mirror] port is error.(1~5)"
		mirror_usage
		exit 0
	fi

	if [ -z "$ports" ]; then
		echo "[mirror] mirrored port is null.(1~5)"
		mirror_usage
		exit 0
	fi

	for i in $ports; do		
		if [ `expr match $i "[0-9]"` = 0 ] || [ $i -lt 1 ] || [ $i -gt 5 ] || [ $i -eq $portid ];then
			echo "[mirror] mirrored port is error.(1~5)"
			mirror_usage
			exit 0
		fi
	done
}
 

print_mirror_info()
{
	config_get state "mirror" state     
	config_get mode "mirror" mode  
	config_get mirrorport "mirror" mirrorport
	config_get mirroredports "mirror" mirroredports

	echo "Mirror state   :  $state" 
	echo "Mirror mode    :  $mode"
	echo "Mirror port    :  $mirrorport"
	echo "Mirrored ports :  $mirroredports"
	echo ""
} 

# init rtl8367s switch port mirror
# $1: state
# $2: mirror mode
# $3: mirror port
# $4: mirrored ports
rtl8367s_switch_port_mirror_init()
{
	if [ "$1" = "on" ]; then		
		#mirror_arg_check $mode $portid "$mirroredPorts"
		enable_port_mirror $2 $3 "$4"
	elif [ "$1" = "off" ]; then
		clear_port_mirror
	else
		echo "[mirror] state is invalid.(on | off)"
		exit 0
	fi
}

# rtl8367s switch port mirror
# $1:op (get|set)
# $2:state (on | off)
# $3:mirror mode (ingress | egress | both)
# $4:mirror port id (1 | 2 | 3 | 4 | 5)
# $5:mirrored port list (1.2.3...)
rtl8367s_switch_port_mirror()
{
	local op=$1
	local state=$2
	local mode=$3
	local portid=$4
	local mirroredPorts=$5	

	#get port mirror info
	if [ "$op" = "get" ]; then
		print_mirror_info
	elif [ "$op" = "set" ]; then
		if [ "$state" = "off" ]; then
			clear_port_mirror
		elif [ "$state" = "on" ]; then
			mirror_arg_check $mode $portid "$mirroredPorts"
			enable_port_mirror $mode $portid "$mirroredPorts"
		else
			echo "[mirror] state is invalid.(on | off)"
			exit 0
		fi

	else
		echo "[mirror] error op. (set | get)"
	fi
}