# CMake generated Testfile for 
# Source directory: /home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake
# Build directory: /home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(RunCMake.Languages "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/Languages" "-DRunCMake_BINARY_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/Languages" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/Languages/RunCMakeTest.cmake")
ADD_TEST(RunCMake.ObjectLibrary "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/ObjectLibrary" "-DRunCMake_BINARY_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/ObjectLibrary" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/ObjectLibrary/RunCMakeTest.cmake")
ADD_TEST(RunCMake.build_command "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/build_command" "-DRunCMake_BINARY_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/build_command" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/build_command/RunCMakeTest.cmake")
ADD_TEST(RunCMake.find_package "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/find_package" "-DRunCMake_BINARY_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/find_package" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/find_package/RunCMakeTest.cmake")
ADD_TEST(RunCMake.include "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/include" "-DRunCMake_BINARY_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/include" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/include/RunCMakeTest.cmake")
ADD_TEST(RunCMake.list "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/bin/cmake" "-DCMAKE_MODULE_PATH=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake" "-DRunCMake_GENERATOR=Unix Makefiles" "-DRunCMake_SOURCE_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/list" "-DRunCMake_BINARY_DIR=/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/list" "-P" "/home/ubuntu/Archer_C7_V5/openwrt/build_dir/host/cmake-2.8.9/Tests/RunCMake/list/RunCMakeTest.cmake")
