#define CONFIG_ATHEROS		1
#define CONFIG_PRODUCT_C7V4		1
#define CONFIG_MACH_QCA956x	1
#define CFG_INIT_STACK_IN_SRAM	1
#define CONFIG_AP152	1
#define __CONFIG_BOARD_NAME ap152
#define CONFIG_BOARD_NAME "ap152"
#define CFG_PLL_FREQ		CFG_PLL_775_650_258
#define CFG_DDR2_DRAGONFLY_CAS_LATENCY		5
#define CFG_ATH_GMAC_NMACS	1
#define CFG_ATH_GE1_IS_CONNECTED 1
#define CONFIG_ATHRS_GMAC_SGMII  1
#define ATH_S17_MAC0_SGMII	1
#define UART_RX18_TX22           1
#define CONFIG_ATHRS_GMAC_SGMII	1
#define CONFIG_ATHRS17_PHY	1
#define ATH_SGMII_FORCED_MODE    1
#define FLASH_SIZE	16
#define TP_FIRMWARE_RECOVERY 1
#define FIRMWARE_RECOVERY_NAME "ArcherC7v4_tp_recovery.bin"
#define FIRMWARE_RECOVERY_IP_ADDR "192.168.0.86"
#define FIRMWARE_RECOVERY_SERVER_IP "192.168.0.66"
#define NM_PTN_TABLE_BASE 0xfc0000
#define NM_FLASH_SIZE 0x1000000
#define NM_PTN_NUM_MAX 32
#define CFG_DOUBLE_BOOT_FACTORY 1
#define CONFIG_CMD_HTTPD 1
#define WEBFAILSAFE_SERVER_IP_ADDR "192.168.0.1"
#define CONFIG_UBOOT_MALLOC_LEN (16*1024*1024)
#define FIRMWARE_RECOVERY_GPIO_SCHEME "C7V4"

/* Automatically generated - do not edit */
#include <configs/board956x.h>
