#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=98

USE_PROCD=1
PROG=/usr/sbin/ntpd

validate_ntp_section() {
	uci_validate_section systime timeserver "${1}" \
		'server:list(host)' 'enabled:bool:1' 'enable_server:bool:0'
}

start_service() {
	local server enabled enable_server peer country server_country

	validate_ntp_section ntp || {
		echo "validation failed"
		return 1
	}

	[ $enabled = 0 ] && return

	[ -z "$server" ] && return

	procd_open_instance
	procd_set_param command "$PROG" -n
	[ "$enable_server" = "1" ] && procd_append_param command -l
	country=$(getfirm COUNTRY)
	server_country=$(uci -c /etc/profile.d get ntp.$country.server)
	if [ ! $server_country ]; then
		server=$(uci -c /etc/profile.d get ntp.ntp.server)
	else 
		server=$server_country" "$(uci -c /etc/profile.d get ntp.ntp.server)
	fi
	for peer in $server; do
		procd_append_param command -p $peer
	done
	procd_set_param respawn
	procd_close_instance
}
