#!/bin/sh
hex()
{
	echo `echo $1 |awk '{printf("%x"),$0}'`
}
setbit()
{
	local x=$1
	local bit=$2
	local val=$3
	local sa=$((1<<$bit))
	if [ $val == 1 ]; then
		hex $(($x | $sa))
	else
		hex $(($x & (~$sa)))
	fi

}

clear_port_mirror()
{
	#the default_port can be any port 
	local cpu_reg=0x0078
	local value=$(swconfig_reg_read $cpu_reg)

	value=$(hex $((($value |0x0F0))))
	swconfig_reg_write $cpu_reg 0x$value
	for i in 2 3 4 5 6; do
		local reg=$(hex $((0x100*$i + 0x4)))
		value=$(swconfig_reg_read $reg)

		value=0x$(setbit $value 2 0)
		swconfig_reg_write $reg $value

		value=0x$(setbit $value 17 0)
		value=0x$(setbit $value 16 0)
		swconfig_reg_write $reg $value

		
		value=0x$(setbit $value 2 1)
		swconfig_reg_write $reg $value

	done

}

# enable port mirror
# $1:mirror mode
# $2:mirror port id
# $3:mirrored port list
enable_port_mirror()
{
	local mode=$1
	local mirrorport=$2
	local mirroredPortlist=$3
	local mirrorCmd=""
	local cpu_reg=0x0078
	local value=$(swconfig_reg_read $cpu_reg)

	value=$(hex $((($value&0xF0F)|($mirrorport<<4))))
	swconfig_reg_write $cpu_reg 0x$value

	for i in 2 3 4 5 6; do
		local reg=$(hex $((0x100*$i + 0x4)))
		value=$(swconfig_reg_read $reg)
		value=0x$(setbit $value 17 0)
		value=0x$(setbit $value 16 0)
		swconfig_reg_write $reg $value

	done
	
	for i in $mirroredPortlist; do		
		local reg=$(hex $((0x100*($i+1) + 0x4)))
		value=$(swconfig_reg_read $reg)
		if [ $mode = "ingress" ]; then
			value=0x$(setbit $value 17 1)
			value=0x$(setbit $value 16 0)
		elif [ $mode = "egress" ]; then
			value=0x$(setbit $value 17 0)
			value=0x$(setbit $value 16 1)
		elif [ $mode = "both" ]; then
			value=0x$(setbit $value 17 1)
			value=0x$(setbit $value 16 1)
		fi
		swconfig_reg_write $reg $value
	done	


}

mirror_usage()
{
	echo ""
	echo "Usage: switch -t mirror -o <get|set> [-s state] [-m mode] [-P mirrorport] [-p mirroredports]"
	echo ""
	echo "Example:"
	echo "       switch -t mirror -o get"
	echo "       switch -t mirror -o set -s on -m ingress -P 3 -p \"1 2 4\" "
	echo ""
}

# check mode mirror port and mirrored portlist
# exit when arg is invalid
# $1: mode
# $2: mirror port
# $3: mirrored ports
mirror_arg_check()
{
	local mode=$1
	local portid=$2
	local ports=$3

    if [ "$mode" != "" ] && [ "$mode" != "ingress" ] && [ "$mode" != "egress" ] && [ "$mode" != "both" ]; then
    	echo "[mirror] mode is error. (ingress | egress | both)"
        mirror_usage
        exit 0 
    fi 

    # check input portid
	if [ -z $portid ] || [ `expr match $portid "[0-9]"` = 0 ] || [ $portid -lt 1 ] || [ $portid -gt 5 ];then
		echo "[mirror] port is error.(1~5)"
		mirror_usage
		exit 0
	fi

	if [ -z "$ports" ]; then
		echo "[mirror] mirrored port is null.(1~5)"
		mirror_usage
		exit 0
	fi

	for i in $ports; do		
		if [ `expr match $i "[0-9]"` = 0 ] || [ $i -lt 1 ] || [ $i -gt 5 ] || [ $i -eq $portid ];then
			echo "[mirror] mirrored port is error.(1~5)"
			mirror_usage
			exit 0
		fi
	done
}
 

print_mirror_info()
{
	config_get state "mirror" state     
	config_get mode "mirror" mode  
	config_get mirrorport "mirror" mirrorport
	config_get mirroredports "mirror" mirroredports

	echo "Mirror state   :  $state" 
	echo "Mirror mode    :  $mode"
	echo "Mirror port    :  $mirrorport"
	echo "Mirrored ports :  $mirroredports"
	echo ""
} 

# init rtl8367s switch port mirror
# $1: state
# $2: mirror mode
# $3: mirror port
# $4: mirrored ports
ar9533_switch_port_mirror_init()
{
	if [ "$1" = "on" ]; then		
		#mirror_arg_check $mode $portid "$mirroredPorts"
		enable_port_mirror $2 $3 "$4"
	elif [ "$1" = "off" ]; then
		clear_port_mirror
	else
		echo "[mirror] state is invalid.(on | off)"
		exit 0
	fi
}

# rtl8367s switch port mirror
# $1:op (get|set)
# $2:state (on | off)
# $3:mirror mode (ingress | egress | both)
# $4:mirror port id (1 | 2 | 3 | 4 | 5)
# $5:mirrored port list (1.2.3...)
ar9533_switch_port_mirror()
{
	local op=$1
	local state=$2
	local mode=$3
	local portid=$4
	local mirroredPorts=$5	

	#get port mirror info
	if [ "$op" = "get" ]; then
		print_mirror_info
	elif [ "$op" = "set" ]; then
		if [ "$state" = "off" ]; then
			clear_port_mirror
		elif [ "$state" = "on" ]; then
			mirror_arg_check $mode $portid "$mirroredPorts"
			enable_port_mirror $mode $portid "$mirroredPorts"
		else
			echo "[mirror] state is invalid.(on | off)"
			exit 0
		fi

	else
		echo "[mirror] error op. (set | get)"
	fi
}

