#!/bin/sh

. /lib/switch/switch_functions

# get port state
# $1: portid
get_port_state()
{
	local port_state=0
	local port_speed=0
	local port_dup_mode=0
	local port_flowcontrol="off"
	
	local port=`get_port_index $i`
	local port_off=$(($port << 8))
	port_off=$((0x3008 | $port_off))
	port_off=`printf "0x%02x" $port_off`
	local val=`ralink-switch reg r $port_off`
	val=`echo "$val" | awk -F '=' '{printf $3}'`
	val=`printf "%d" 0x$val`
	local bit=`get_bit_value $val 0`
	if [ $bit -eq 1 ]; then
		port_state="connected"

		# get duplex mode
		local duplex=`get_bit_value $val 1`
		if [ $duplex -eq 1 ]; then
			port_dup_mode="Full"
		else
			port_dup_mode="Half"
		fi

		#get speed
		local speed1=`get_bit_value $val 2`
		local speed2=`get_bit_value $val 3`
		if [ $speed1 -eq 0 -a $speed2 -eq 1 ]; then
			port_speed="1000M"
		elif [ $speed1 -eq 1 -a $speed2 -eq 0 ]; then
			port_speed="100M"
		elif [ $speed1 -eq 0 -a $speed2 -eq 0 ]; then
			port_speed="10M"
		else
			port_speed="0M"
		fi

		val=`swconfig_phy_reg_read $port $PHY_AN_ADVERTISEMENT_REG`
		bit=`get_bit_value $val 10`
		if [ $bit -eq 1 ]; then
			port_flowcontrol="on"
		else
			port_flowcontrol="off"
		fi
	else
		port_state="disconnected"

		port_speed="---"
		port_dup_mode="---"
		port_flowcontrol="---"
	fi	

	echo "Port $port:"
	echo "   state       : $port_state "
	echo "   speed       : $port_speed "
	echo "   dup_mode    : $port_dup_mode "
	echo "   flowcontrol : $port_flowcontrol "
	echo ""
}


stata_arg_check()
{
	local portsid=$1

	for i in $portsid; do
		if [ `expr match $i "[0-9]"` = 0 ] || [ $i -lt 1 ] || [ $i -gt $MAX_PORT_NUM ] ;then
		echo "[state] port is invalid. "
		exit 0
		fi
	done
}
# mt7621 switch get port state
# $1: op (get)
# $2: portsid (1.2.3.4.5...)
mt7621_switch_port_state()
{
	local op=$1
	local portsid=$2

	if [ $op = "get" ]; then	
		stata_arg_check "$portsid"
		for i in $portsid; do			
			get_port_state $i
		done
	else
		echo "[state] error op. (get)"
	fi
}