#!/bin/sh
. /lib/functions.sh
. /lib/functions/system.sh

include /lib/upgrade

FIRMWARE_BIN=$1
#rewrite by scripts/ptn_offset_set.sh when compiling dkmgt module.
PTN_TABLE_OFFSET=0x01900000

real_ptn_off=${PTN_TABLE_OFFSET}
$(cat /proc/cmdline | grep -q "DKMGT_IMAGE_TYPE=ubi") && {
	real_ptn_off=0x0 #ubi id
	ubi_opts="-w ubi"
}

# check cmd format.
if [ -z "${FIRMWARE_BIN}" ]; then
	echo "[C] Invalid args ! format should be : fwup <firmware.bin> ." 2>&1 1>/dev/console
	exit 1
fi

if [ ! -e "${FIRMWARE_BIN}" ]; then
	echo "[C] Firmware [${FIRMWARE_BIN}] not exist!" 2>&1 1>/dev/console
	exit 1
fi

# check if firmware.bin exists.
FIRMWARE_MTD=$(find_mtd_part "firmware")
if [ -z "${FIRMWARE_MTD}" ]; then
	echo "[C] MTD[firmware] not found, failed to upgrade firmware!" 2>&1 1>/dev/console
	exit 1
fi

echo "[C] FIRMWARE_MTD is ${FIRMWARE_MTD}, FIRMWARE_BIN is ${FIRMWARE_BIN}" 2>&1 1>/dev/console

# check firmware format.
dkmgt_firmware_upgrade -C -f ${FIRMWARE_MTD} -p ${real_ptn_off} -u ${FIRMWARE_BIN} ${ubi_opts}
RC=$?

if [ ${RC} -ne 0 ]; then
	echo "[R] Firmware is Invalid, Abort!!." 2>&1 1>/dev/console
	exit 1
fi

echo "[R] Firmware is OK, will upgrade it." 2>&1 1>/dev/console

exit 0
