package-basefs:= \
	base-files \
	feeds/iplatform/cfg-loader \
	feeds/iplatform/luci-app-auth \
	feeds/iplatform/luci-app-account \
	feeds/iplatform/luci-app-index \
	feeds/iplatform/luci-app-firmware \
	feeds/iplatform/luci-app-tools \
	feeds/iplatform/logModel \
	feeds/iplatform/netconf-ipc \
	feeds/iplatform/nvrammanager \
	feeds/iplatform/systemtools \
	feeds/iplatform/webpages-mini \
	feeds/iplatform/wlan-mtk \
	feeds/iplatform/wirelessd \
	feeds/iplatform/libcloud-cli \
	feeds/iplatform/libcloud-api \
	feeds/iplatform/libcJSON \
	feeds/iplatform/cares \
	feeds/iplatform/recover-manager \
	feeds/iplatform/hi_cipher_handle \
	feeds/iplatform/ledd \
	feeds/iplatform/button \
	feeds/iplatform/timed \
	feeds/iplatform/ntime-onlined \
	feeds/iplatform/libcMD5 \
	feeds/iplatform/libcBase64 \
	feeds/luci/luci-base \
	feeds/luci/luci-lib-ip \
	feeds/luci/luci-lib-nixio \
	feeds/luci/luci-theme-bootstrap \
	feeds/luci/luci-lib-json \
	feeds/packages/expat \
	feeds/packages/luaexpat \
	feeds/packages/sysstat \
	feeds/packages/ntpclient \
	kernel/linux \
	libs/libjson-c \
	libs/libnl-tiny \
	libs/libubox \
	libs/toolchain \
	libs/zlib \
	libs/cyassl \
	libs/mbedtls \
	libs/mbedtls-hisi \
	network/config/netifd \
	network/services/uhttpd \
	network/services/dnsmasq \
	network/utils/wireless-tools \
	network/utils/iwinfo \
	network/utils/curl \
	network/utils/iperf3 \
	system/procd \
	system/ubox \
	system/ubus \
	system/uci \
	system/rpcd \
	system/opkg \
	system/usign \
	utils/busybox \
	utils/jsonfilter \
	utils/lua
package-basefs-volatile:= 
