#!/bin/sh
cat /etc/resolv.conf
echo "set nameserver 8.8.8.8"
echo "nameserver 8.8.8.8" > /etc/resolv.conf
cat /etc/resolv.conf
sleep 1
echo "starting alexa demo app"
GST_PLUGIN_PATH_1_0=/usr/lib/gstreamer-1.0 TZ=UTC /usr/bin/SampleApp /share/alexa/AlexaClientSDKConfig.json DEBUG1
