#############################################################
#
# sdk 
#
#############################################################
SDK_VERSION = 1.0
SDK_SITE = $(TOPDIR)/tplink/sdk/sdk_dummy
SDK_SITE_METHOD = local
SDK_AUTORECONF = YES
SDK_INSTALL_STAGING = NO
SDK_INSTALL_TARGET =  YES

SDK_TARGET_DIR = $(call qstrip,$(BR2_TPLINK_SDK_DIR))
SDK_PROJECT_NAME = $(call qstrip,$(BR2_TPLINK_PROJECT_NAME))
SDK_DEBUG_FLAG = $(call qstrip,$(BR2_TPLINK_SDK_DBG))
#PP_TYPE DX_ALL PX_ALL DX/PX
SDK_SH_BUILD_PARAM += DX_ALL
#CPU & CHIPSET

SDK_SH_BUILD_PARAM += ARMv7_LK_4_4

#OPTIONAL PARAMETERS
SDK_SH_BUILD_PARAM +=  CUST NOKERNEL CPSS_ENABLER_NOKM NOLUA NOGALTIS UTF_NO TM_NO NOLINK
#TPLINK PARAMETERS
#SDK_SH_BUILD_PARAM += TPLINK_$(SDK_PROJECT_NAME)
SDK_SH_BUILD_PARAM += TPLINK_CUSTOM TPLINK_$(SDK_PROJECT_NAME)
SDK_BUILD_DIR = $(SDK_TARGET_DIR)/$(SDK_PROJECT_NAME)

define SDK_BUILD_CMDS
endef

define SDK_CLEAN_CMDS
endef

define SDK_INSTALL_TARGET_CMDS
endef

$(eval $(tplink-autotools-package))
